#!/bin/bash
sbatch batch_PMT_0.sh
sbatch batch_PMT_1.sh
sbatch batch_PMT_2.sh
sbatch batch_PMT_3.sh
sbatch batch_PMT_4.sh
sbatch batch_PMT_5.sh
sbatch batch_PMT_6.sh
sbatch batch_PMT_7.sh
sbatch batch_PMT_8.sh
sbatch batch_PMT_9.sh
sbatch batch_PMT_10.sh
sbatch batch_PMT_11.sh
sbatch batch_PMT_12.sh
sbatch batch_PMT_13.sh
sbatch batch_PMT_14.sh
sbatch batch_PMT_15.sh
sbatch batch_PMT_16.sh
sbatch batch_PMT_17.sh
sbatch batch_PMT_18.sh
sbatch batch_PMT_19.sh
sbatch batch_PMT_20.sh
sbatch batch_PMT_21.sh
sbatch batch_PMT_22.sh
sbatch batch_PMT_23.sh
sbatch batch_PMT_24.sh
sbatch batch_PMT_25.sh
sbatch batch_PMT_26.sh
sbatch batch_PMT_27.sh
sbatch batch_PMT_28.sh
sbatch batch_PMT_29.sh
sbatch batch_PMT_30.sh
sbatch batch_PMT_31.sh
sbatch batch_PMT_32.sh
sbatch batch_PMT_33.sh
sbatch batch_PMT_34.sh
sbatch batch_PMT_35.sh
sbatch batch_PMT_36.sh
sbatch batch_PMT_37.sh
sbatch batch_PMT_38.sh
sbatch batch_PMT_39.sh
sbatch batch_PMT_40.sh
sbatch batch_PMT_41.sh
sbatch batch_PMT_42.sh
sbatch batch_PMT_43.sh
sbatch batch_PMT_44.sh
sbatch batch_PMT_45.sh
sbatch batch_PMT_46.sh
sbatch batch_PMT_47.sh
sbatch batch_PMT_48.sh
sbatch batch_PMT_49.sh
sbatch batch_PMT_50.sh
sbatch batch_PMT_51.sh
sbatch batch_PMT_52.sh
sbatch batch_PMT_53.sh
sbatch batch_PMT_54.sh
sbatch batch_PMT_55.sh
sbatch batch_PMT_56.sh
sbatch batch_PMT_57.sh
sbatch batch_PMT_58.sh
sbatch batch_PMT_59.sh
sbatch batch_PMT_60.sh
sbatch batch_PMT_61.sh
sbatch batch_PMT_62.sh
sbatch batch_PMT_63.sh
sbatch batch_PMT_64.sh
sbatch batch_PMT_65.sh
sbatch batch_PMT_66.sh
sbatch batch_PMT_67.sh
sbatch batch_PMT_68.sh
sbatch batch_PMT_69.sh
sbatch batch_PMT_70.sh
sbatch batch_PMT_71.sh
sbatch batch_PMT_72.sh
sbatch batch_PMT_73.sh
sbatch batch_PMT_74.sh
sbatch batch_PMT_75.sh
sbatch batch_PMT_76.sh
sbatch batch_PMT_77.sh
sbatch batch_PMT_78.sh
sbatch batch_PMT_79.sh
sbatch batch_PMT_80.sh
sbatch batch_PMT_81.sh
sbatch batch_PMT_82.sh
sbatch batch_PMT_83.sh
sbatch batch_PMT_84.sh
sbatch batch_PMT_85.sh
sbatch batch_PMT_86.sh
sbatch batch_PMT_87.sh
sbatch batch_PMT_88.sh
sbatch batch_PMT_89.sh
sbatch batch_PMT_90.sh
sbatch batch_PMT_91.sh
sbatch batch_PMT_92.sh
sbatch batch_PMT_93.sh
sbatch batch_PMT_94.sh
sbatch batch_PMT_95.sh
sbatch batch_PMT_96.sh
sbatch batch_PMT_97.sh
sbatch batch_PMT_98.sh
sbatch batch_PMT_99.sh
sbatch batch_PMT_100.sh
sbatch batch_PMT_101.sh
sbatch batch_PMT_102.sh
sbatch batch_PMT_103.sh
sbatch batch_PMT_104.sh
sbatch batch_PMT_105.sh
sbatch batch_PMT_106.sh
sbatch batch_PMT_107.sh
sbatch batch_PMT_108.sh
sbatch batch_PMT_109.sh
sbatch batch_PMT_110.sh
sbatch batch_PMT_111.sh
sbatch batch_PMT_112.sh
sbatch batch_PMT_113.sh
sbatch batch_PMT_114.sh
sbatch batch_PMT_115.sh
sbatch batch_PMT_116.sh
